pipeline{
    agent any
    environment {
        app_version = 'v1'
        rollback = 'true'
        DATABASE_URI = credentials("DATABASE_URI")
    }
    stages{
        stage("Testing"){
            steps{
                sh "bash jenkins/test.sh"
            }
        }
        stage("Build & Push"){
            steps{
                sh "docker-compose build && docker-compose push"
            }
        }
        stage("Config Management"){
            steps{
                sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash jenkins/deploy.sh"
            }
        }
    }

}